// Copyright (c) 2013-2015 Sandstorm Development Group, Inc. and contributors
// Licensed under the MIT License:
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/**
 * ZAP is a highly efficient binary data format and
 * remote procedure call protocol.
 *
 * This package contains the runtime library to support code generated by zapc-dlang, a schema
 * compiler plugin written in C++. It does not support RPC.
 *
 */
module zap;

public import zap.AnyPointer;
public import zap.Arena;
public import zap.ArrayInputStream;
public import zap.ArrayOutputStream;
public import zap.BufferedInputStream;
public import zap.BufferedInputStreamWrapper;
public import zap.BufferedOutputStream;
public import zap.BufferedOutputStreamWrapper;
public import zap.BuilderArena;
public import zap.Constants;
public import zap.Data;
public import zap.DataList;
public import zap.DecodeException;
public import zap.ElementSize;
public import zap.EnumList;
public import zap.FarPointer;
public import zap.FileDescriptor;
public import zap.GeneratedClassSupport;
public import zap.ListBuilder;
public import zap.ListList;
public import zap.ListPointer;
public import zap.ListReader;
public import zap.MemoryMapped;
public import zap.MessageBuilder;
public import zap.MessageReader;
public import zap.PackedInputStream;
public import zap.PackedOutputStream;
public import zap.PrimitiveList;
public import zap.ReaderArena;
public import zap.ReaderOptions;
public import zap.SegmentBuilder;
public import zap.SegmentReader;
public import zap.Serialize;
public import zap.SerializePacked;
public import zap.StructBuilder;
public import zap.StructList;
public import zap.StructPointer;
public import zap.StructReader;
public import zap.StructSize;
public import zap.Text;
public import zap.TextList;
public import zap.Void;
public import zap.WireHelpers;
public import zap.WirePointer;
